Add retries

diff --git a/.github/workflows/deploy_check.yml b/.github/workflows/deploy_check.yml
--- a/.github/workflows/deploy_check.yml
+++ b/.github/workflows/deploy_check.yml
@@ -57,6 +57,24 @@ jobs:
         if: steps.duplicate_check.outputs.should_skip != 'true'
         timeout-minutes: 60
         run: |
-          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyccel[test]=="${TEST_VERSION}"
+          WAIT=20
+          SUCCESS=0
+          for i in {1..5}; do
+            echo "Attempt $i: Installing pyccel==${TEST_VERSION}..."""
+            if python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyccel[test]=="${TEST_VERSION}"
+            then
+              SUCCESS=1
+              break
+            else
+              echo "Install failed. Retrying in $WAIT seconds..."
+              sleep $WAIT
+            fi
+          done
+
+          # Final check
+          if [ "$SUCCESS" -ne 1 ]; then
+            echo "ERROR: Failed to install pyccel==${TEST_VERSION}."
+            exit 1
+          fi
           pyccel-test
         shell: bash
